name: Testing Pipeline
trigger:
  batch: false
stages:
- stage: main
  displayName: Main
  jobs:
  - job: sdist
    displayName: Build sdist
    continueOnError: true
    steps:
    - bash:
      - python setup.py sdist --format=zip
      displayName: Build
      failOnStderr: true
    - displayName: Publish
