name: Testing Pipeline
trigger:
  batch: false
stages:
- stage: main
  displayName: Main
  jobs:
  - job: sdist
    displayName: Build sdist
    continue_on_error: true
    steps:
    - display_name: Build
      bash:
      - python setup.py sdist --format=zip
      failOnStderr: true
    - display_name: Publish
