name: CI
'on':
  push:
    branches:
    - master
    tags:
    - v*
  pull_request:
    branches:
    - '*'
jobs:
  verify_up_to_date:
    name: Verify up to date
    runs-on: ubuntu-latest
    steps:
    - name: Set up CPython 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: x64
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install ciborg
      run: |-
        python -m pip install --upgrade pip setuptools
        python -m pip install "."
    - name: Generate
      run: python -m ciborg github --configuration ciborg.json --output .github/workflows/ci.yml
    - name: Verify
      run: '[ -z "$(git status --porcelain)" ]'
  sdist:
    name: Build sdist
    runs-on: ubuntu-latest
    steps:
    - name: Set up CPython 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: x64
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |-
        python -m pip install --quiet --upgrade pip
        python -m pip install --quiet --upgrade pep517
        python -m pep517.build --source --out-dir dist/ .
    - name: Publish
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/
  bdist:
    name: Build pure wheel
    runs-on: ubuntu-latest
    steps:
    - name: Set up CPython 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: x64
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |-
        python -m pip install --quiet --upgrade pip
        python -m pip install --quiet --upgrade pep517
        python -m pep517.build --binary --out-dir dist/ .
    - name: Publish
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/
  tox_linux_py36_bdist:
    name: Tox - py36
    runs-on: ubuntu-latest
    needs:
    - bdist
    steps:
    - name: Set up CPython 3.6
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'
        architecture: x64
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: ./
    - name: Select distribution file
      run: |-
        ls ${PWD}/dist/*
        echo ::set-env name=DIST_FILE_PATH::$(ls ${PWD}/dist/*.whl)
    - name: Tox
      run: |-
        python -m pip install --quiet --upgrade pip setuptools wheel
        python -m pip install tox
        python -m tox --installpkg="${DIST_FILE_PATH}"
      env:
        DIST_FILE_PATH: $(DIST_FILE_PATH)
        TOXENV: py36
  tox_linux_py38_sdist:
    name: Tox - py38
    runs-on: ubuntu-latest
    needs:
    - sdist
    steps:
    - name: Set up CPython 3.8
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: x64
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: ./
    - name: Select distribution file
      run: |-
        ls ${PWD}/dist/*
        echo ::set-env name=DIST_FILE_PATH::$(ls ${PWD}/dist/*.tar.gz)
    - name: Tox
      run: |-
        python -m pip install --quiet --upgrade pip setuptools wheel
        python -m pip install tox
        python -m tox --installpkg="${DIST_FILE_PATH}"
      env:
        DIST_FILE_PATH: $(DIST_FILE_PATH)
        TOXENV: py38
  tox_linux_py38_bdist:
    name: Tox - py38
    runs-on: ubuntu-latest
    needs:
    - bdist
    steps:
    - name: Set up CPython 3.8
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: x64
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: ./
    - name: Select distribution file
      run: |-
        ls ${PWD}/dist/*
        echo ::set-env name=DIST_FILE_PATH::$(ls ${PWD}/dist/*.whl)
    - name: Tox
      run: |-
        python -m pip install --quiet --upgrade pip setuptools wheel
        python -m pip install tox
        python -m tox --installpkg="${DIST_FILE_PATH}"
      env:
        DIST_FILE_PATH: $(DIST_FILE_PATH)
        TOXENV: py38
  tox_macos_py38_bdist:
    name: Tox - py38
    runs-on: macOS-latest
    needs:
    - bdist
    steps:
    - name: Set up CPython 3.8
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: x64
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: ./
    - name: Select distribution file
      run: |-
        ls ${PWD}/dist/*
        echo ::set-env name=DIST_FILE_PATH::$(ls ${PWD}/dist/*.whl)
    - name: Tox
      run: |-
        python -m pip install --quiet --upgrade pip setuptools wheel
        python -m pip install tox
        python -m tox --installpkg="${DIST_FILE_PATH}"
      env:
        DIST_FILE_PATH: $(DIST_FILE_PATH)
        TOXENV: py38
  tox_windows_py38_bdist:
    name: Tox - py38
    runs-on: windows-latest
    needs:
    - bdist
    steps:
    - name: Set up CPython 3.8
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: x64
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: ./
    - name: Select distribution file
      run: |-
        ls ${PWD}/dist/*
        echo ::set-env name=DIST_FILE_PATH::$(ls ${PWD}/dist/*.whl)
    - name: Tox
      run: |-
        python -m pip install --quiet --upgrade pip setuptools wheel
        python -m pip install tox
        python -m tox --installpkg="${DIST_FILE_PATH}"
      env:
        DIST_FILE_PATH: $(DIST_FILE_PATH)
        TOXENV: py38
  all:
    name: All
    runs-on: ubuntu-latest
    needs:
    - verify_up_to_date
    - sdist
    - bdist
    - tox_linux_py36_bdist
    - tox_linux_py38_sdist
    - tox_linux_py38_bdist
    - tox_macos_py38_bdist
    - tox_windows_py38_bdist
    steps:
    - name: Set up CPython 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: x64
    - name: This
      run: python -m this
